/**
 * Musical key <-> Camelot wheel.
 *
 * rekordbox shows classical names (`Ebm`, `Am`) in the Key column and Camelot
 * codes (`5A`) in comments generated by many DJ tools, so we map both ways.
 */
const MINOR = ["Abm", "Ebm", "Bbm", "Fm", "Cm", "Gm", "Dm", "Am", "Em", "Bm", "F#m", "Dbm"];
const MAJOR = ["B", "F#", "Db", "Ab", "Eb", "Bb", "F", "C", "G", "D", "A", "E"];

const ALIASES: Record<string, string> = {
  "G#m": "Abm", "D#m": "Ebm", "A#m": "Bbm", "C#m": "Dbm", "Gbm": "F#m",
  "Gb": "F#", "C#": "Db", "G#": "Ab", "D#": "Eb", "A#": "Bb",
};

export function normalizeKey(key: string): string {
  const k = key.trim();
  return ALIASES[k] ?? k;
}

/** `Ebm` -> `2A`, `C` -> `8B`. Empty string when the key is not recognised. */
export function toCamelot(key: string): string {
  const k = normalizeKey(key);
  const minor = MINOR.indexOf(k);
  if (minor >= 0) return `${minor + 1}A`;
  const major = MAJOR.indexOf(k);
  if (major >= 0) return `${major + 1}B`;
  return "";
}

/** `2A` -> `Ebm`. Empty string when the code is malformed. */
export function fromCamelot(code: string): string {
  const m = /^(\d{1,2})([AB])$/i.exec(code.trim());
  if (!m?.[1] || !m[2]) return "";
  const n = Number(m[1]);
  if (n < 1 || n > 12) return "";
  return (m[2].toUpperCase() === "A" ? MINOR : MAJOR)[n - 1] ?? "";
}

/** Keys that mix harmonically: same code, +/-1 on the wheel, and the relative major/minor. */
export function compatibleKeys(key: string): string[] {
  const code = toCamelot(key);
  if (!code) return [];
  const n = Number(code.slice(0, -1));
  const letter = code.slice(-1);
  const other = letter === "A" ? "B" : "A";
  const wrap = (x: number) => ((x - 1 + 12) % 12) + 1;
  return [`${n}${other}`, `${wrap(n - 1)}${letter}`, `${wrap(n + 1)}${letter}`].map(fromCamelot).filter(Boolean);
}

/**
 * How far the Traffic Light reaches around the loaded track's key.
 *
 * rekordbox's own definition, from its Preferences tooltip [DOC]: for a
 * loaded track in 2A —
 *   Same Key       2A
 *   Related Key 1  2A/2B
 *   Related Key 2  2A/2B/1A/3A
 *   Related Key 3  2A/2B/1A/3A/1B/3B
 */
export type TrafficLightReach = "same" | "related1" | "related2" | "related3";

/**
 * The Camelot codes the Traffic Light lights for a track in `key`, or none
 * when the key is not on the wheel.
 */
export function trafficLightCodes(key: string, reach: TrafficLightReach): string[] {
  const code = toCamelot(key);
  if (!code) return [];
  const n = Number(code.slice(0, -1));
  const letter = code.slice(-1);
  const other = letter === "A" ? "B" : "A";
  const wrap = (x: number) => ((x - 1 + 12) % 12) + 1;
  const codes = [code];
  if (reach !== "same") codes.push(`${n}${other}`);
  if (reach === "related2" || reach === "related3") {
    codes.push(`${wrap(n - 1)}${letter}`, `${wrap(n + 1)}${letter}`);
  }
  if (reach === "related3") codes.push(`${wrap(n - 1)}${other}`, `${wrap(n + 1)}${other}`);
  return codes;
}

/** Whether a row in `key` lights up against a loaded track in `reference`. */
export function trafficLightLit(key: string, reference: string, reach: TrafficLightReach): boolean {
  const code = toCamelot(key);
  return code !== "" && trafficLightCodes(reference, reach).includes(code);
}

