/**
 * Interface icons. GENERATED by `pnpm icons` from `design/icons/ui/*.svg` —
 * edit the SVGs, not this file.
 *
 * Every icon paints in `currentColor`, so colour comes from the CSS token on
 * whatever contains it rather than from the icon.
 */
import type { SVGProps } from "react";

type IconProps = SVGProps<SVGSVGElement>;

export const CollectionIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <circle cx="8" cy="8" r="5.4" fill="none" stroke="currentColor" strokeWidth="1.4"/> <circle cx="8" cy="8" r="1.5" fill="currentColor"/>
  </svg>
);

export const CutIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <path d="M4.2 2.6v10.8" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/> <path d="M11.8 2.6v10.8" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/> <path d="M13.4 3.4L2.6 12.6" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
  </svg>
);

export const DeviceIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <rect x="4.2" y="1.6" width="7.6" height="9.4" rx="1.2" fill="none" stroke="currentColor" strokeWidth="1.4"/> <path d="M6.4 11v2.2h3.2V11" fill="none" stroke="currentColor" strokeWidth="1.4"/> <path d="M6.6 4.2h2.8" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/>
  </svg>
);

export const DiscIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <path fill="currentColor" fillRule="evenodd" d="M8 2.2a5.8 5.8 0 1 0 0 11.6 5.8 5.8 0 0 0 0-11.6zm0 4.1a1.7 1.7 0 1 0 0 3.4 1.7 1.7 0 0 0 0-3.4z"/>
  </svg>
);

export const EjectIcon = (props: IconProps) => (
  <svg viewBox="0 0 26 29" aria-hidden focusable="false" {...props}>
    <path fill="currentColor" d="M13 0 26 18H0z"/> <rect fill="currentColor" x="0" y="23" width="26" height="6"/>
  </svg>
);

export const FilterIcon = (props: IconProps) => (
  <svg viewBox="0 0 11 11" aria-hidden focusable="false" {...props}>
    <rect x="0.5" y="0" width="2" height="11" fill="currentColor"/><rect x="4.5" y="0" width="6" height="11" fill="currentColor"/>
  </svg>
);

export const FolderIcon = (props: IconProps) => (
  <svg viewBox="0 0 14 12" aria-hidden focusable="false" {...props}>
    <path d="M0 2h5l1.5 1.5H14V11H0z" fill="currentColor"/>
  </svg>
);

export const GearIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <g fill="currentColor"> <rect x="6.9" y="0.6" width="2.2" height="3.2" transform="rotate(0 8 8)"/> <rect x="6.9" y="0.6" width="2.2" height="3.2" transform="rotate(45 8 8)"/> <rect x="6.9" y="0.6" width="2.2" height="3.2" transform="rotate(90 8 8)"/> <rect x="6.9" y="0.6" width="2.2" height="3.2" transform="rotate(135 8 8)"/> <rect x="6.9" y="0.6" width="2.2" height="3.2" transform="rotate(180 8 8)"/> <rect x="6.9" y="0.6" width="2.2" height="3.2" transform="rotate(225 8 8)"/> <rect x="6.9" y="0.6" width="2.2" height="3.2" transform="rotate(270 8 8)"/> <rect x="6.9" y="0.6" width="2.2" height="3.2" transform="rotate(315 8 8)"/> <path fillRule="evenodd" d="M8 1.7A6.3 6.3 0 1 0 8 14.3 6.3 6.3 0 0 0 8 1.7zm0 2.7a3.6 3.6 0 1 1 0 7.2 3.6 3.6 0 0 1 0-7.2z"/> </g>
  </svg>
);

export const HeadphonesIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <path d="M2.4 10.4V8.4a5.6 5.6 0 0 1 11.2 0v2.0" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/> <rect x="1.3" y="9.7" width="2.9" height="4.4" rx="1.35" fill="currentColor"/> <rect x="11.8" y="9.7" width="2.9" height="4.4" rx="1.35" fill="currentColor"/>
  </svg>
);

export const HistoryIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <circle cx="8" cy="8" r="5.6" fill="none" stroke="currentColor" strokeWidth="1.4"/> <path d="M8 4.6V8l2.6 1.6" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
);

export const InfoIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <circle cx="8" cy="8" r="6.4" fill="currentColor"/> <rect x="7.1" y="6.6" width="1.8" height="5.0" rx="0.6" fill="#000"/> <circle cx="8" cy="4.6" r="1.05" fill="#000"/>
  </svg>
);

export const LayoutBrowserIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <rect x="1.5" y="3.4" width="13" height="9.2" fill="none" stroke="currentColor" strokeWidth="1.4"/><path d="M1.5 6.6h13" stroke="currentColor" strokeWidth="1.4"/>
  </svg>
);

export const LayoutDualIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <rect x="1.5" y="5.4" width="8.4" height="7.2" fill="none" stroke="currentColor" strokeWidth="1.4"/><rect x="6.1" y="3.4" width="8.4" height="7.2" fill="none" stroke="currentColor" strokeWidth="1.4"/>
  </svg>
);

export const LayoutOneIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <rect x="1.5" y="4" width="13" height="8" fill="none" stroke="currentColor" strokeWidth="1.4"/><rect x="3.8" y="6.4" width="3.2" height="3.2" fill="currentColor"/>
  </svg>
);

export const LayoutSimpleIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <rect x="1.5" y="5.6" width="13" height="4.8" fill="none" stroke="currentColor" strokeWidth="1.4"/>
  </svg>
);

export const LayoutTwoIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <rect x="1.5" y="3" width="13" height="4.4" fill="none" stroke="currentColor" strokeWidth="1.4"/><rect x="1.5" y="8.6" width="13" height="4.4" fill="none" stroke="currentColor" strokeWidth="1.4"/>
  </svg>
);

export const ListIcon = (props: IconProps) => (
  <svg viewBox="0 0 14 12" aria-hidden focusable="false" {...props}>
    <rect x="1" y="1" width="12" height="10" fill="none" stroke="currentColor" strokeWidth="1.4"/> <path d="M1 4h12M1 7.5h12M4.5 4v7" stroke="currentColor" strokeWidth="1.4"/>
  </svg>
);

export const LockIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <path d="M5.1 7.4V5.4a2.9 2.9 0 0 1 5.8 0v2.0" fill="none" stroke="currentColor" strokeWidth="1.5"/> <rect x="3.2" y="7.2" width="9.6" height="7.0" rx="1.1" fill="currentColor"/>
  </svg>
);

export const MetronomeIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <rect x="2.6" y="8.4" width="2.4" height="5.4" fill="currentColor"/> <rect x="6.8" y="4.6" width="2.4" height="9.2" fill="currentColor"/> <rect x="11.0" y="6.8" width="2.4" height="7.0" fill="currentColor"/>
  </svg>
);

export const MyTagIcon = (props: IconProps) => (
  <svg viewBox="0 0 18 18" aria-hidden focusable="false" {...props}>
    <path fillRule="evenodd" d="M13.6 4.4 8.7 4 2 10.7 7.4 16l6.7-6.7zM11 8.5a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3z" fill="currentColor"/>
  </svg>
);

export const NoteIcon = (props: IconProps) => (
  <svg viewBox="0 0 14 12" aria-hidden focusable="false" {...props}>
    <path d="M9 0v8.2a2.3 2.3 0 1 1-1.4-2.1V2.2L4 3.2v6.2a2.3 2.3 0 1 1-1.4-2.1V1.6z" fill="currentColor"/>
  </svg>
);

export const RelatedIcon = (props: IconProps) => (
  <svg viewBox="0 0 18 18" aria-hidden focusable="false" {...props}>
    <circle cx="12" cy="6" r="2" fill="currentColor"/> <circle cx="6" cy="12" r="2" fill="currentColor"/> <path d="M6 12 12 6" stroke="currentColor" strokeWidth="1"/>
  </svg>
);

export const SortDownIcon = (props: IconProps) => (
  <svg viewBox="0 0 12 12" aria-hidden focusable="false" {...props}>
    <path d="M6 0.6v9.9M2.2 6.7 6 10.5l3.8-3.8" fill="none" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
);

export const SortUpIcon = (props: IconProps) => (
  <svg viewBox="0 0 12 12" aria-hidden focusable="false" {...props}>
    <path d="M6 11.4V1.5M2.2 5.3 6 1.5l3.8 3.8" fill="none" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
);

export const SubBrowseIcon = (props: IconProps) => (
  <svg viewBox="0 0 18 18" aria-hidden focusable="false" {...props}>
    <rect x="3" y="4" width="6" height="10" fill="currentColor"/> <rect x="3.5" y="4.5" width="11" height="9" fill="none" stroke="currentColor" strokeWidth="1"/>
  </svg>
);

export const SuggestIcon = (props: IconProps) => (
  <svg viewBox="0 0 18 18" aria-hidden focusable="false" {...props}>
    <path d="M9 3v12M3.8 6l10.4 6M3.8 12l10.4-6" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/> <circle cx="9" cy="9" r="2.6" fill="none" stroke="currentColor" strokeWidth="1"/>
  </svg>
);

export const TickIcon = (props: IconProps) => (
  <svg viewBox="0 0 12 8" aria-hidden focusable="false" {...props}>
    <path d="M1 4.1L4.1 7 11 1" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
);

export const TwistyIcon = (props: IconProps) => (
  <svg viewBox="0 0 8 8" aria-hidden focusable="false" {...props}>
    <path d="m2.6 1.4 3 2.6-3 2.6" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
);
