/**
 * Interface icons. GENERATED by `pnpm icons` from `design/icons/ui/*.svg` —
 * edit the SVGs, not this file.
 *
 * Every icon paints in `currentColor`, so colour comes from the CSS token on
 * whatever contains it rather than from the icon.
 */
import type { SVGProps } from "react";

type IconProps = SVGProps<SVGSVGElement>;

export const ArtworkDeleteIcon = (props: IconProps) => (
  <svg viewBox="0 0 20 22" aria-hidden focusable="false" {...props}>
    <path d="M10 10 6 5h2.6V0h2.8v5H14z" fill="currentColor"/> <rect x="4" y="11" width="12" height="1.6" fill="currentColor"/> <path fillRule="evenodd" fill="currentColor" d="M5.5 13.6h9l-.8 8.4H6.3zM7.6 15v5.5h.8V15zm2 0v5.5h.8V15zm2 0v5.5h.8V15z"/>
  </svg>
);

export const ArtworkImportIcon = (props: IconProps) => (
  <svg viewBox="0 0 20 22" aria-hidden focusable="false" {...props}>
    <path d="M10 1 14 6h-2.6v5h-2.8V6H6z" fill="currentColor"/> <path d="M1 12h6l1.6 1.6H19V21H1z" fill="currentColor"/>
  </svg>
);

export const ClearCircleIcon = (props: IconProps) => (
  <svg viewBox="0 0 11 11" aria-hidden focusable="false" {...props}>
    <path fillRule="evenodd" fill="currentColor" d="M5.5 0a5.5 5.5 0 1 1 0 11 5.5 5.5 0 0 1 0-11Zm2.83 3.38-.71-.71L5.5 4.79 3.38 2.67l-.71.71L4.79 5.5 2.67 7.62l.71.71L5.5 6.21l2.12 2.12.71-.71L6.21 5.5Z"/>
  </svg>
);

export const CollectionIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <circle cx="8" cy="8" r="5.4" fill="none" stroke="currentColor" strokeWidth="1.4"/> <circle cx="8" cy="8" r="1.5" fill="currentColor"/>
  </svg>
);

export const CommentIcon = (props: IconProps) => (
  <svg viewBox="0 0 12 10" aria-hidden focusable="false" {...props}>
    <path fill="currentColor" d="M2.2 0h7.6A2.2 2.2 0 0 1 12 2.2v2.6A2.2 2.2 0 0 1 9.8 7H6.1L2 10V7A2.2 2.2 0 0 1 0 4.8V2.2A2.2 2.2 0 0 1 2.2 0Z"/>
  </svg>
);

export const CutIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <path d="M4.2 2.6v10.8" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/> <path d="M11.8 2.6v10.8" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/> <path d="M13.4 3.4L2.6 12.6" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
  </svg>
);

export const DeviceIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <rect x="4.2" y="1.6" width="7.6" height="9.4" rx="1.2" fill="none" stroke="currentColor" strokeWidth="1.4"/> <path d="M6.4 11v2.2h3.2V11" fill="none" stroke="currentColor" strokeWidth="1.4"/> <path d="M6.6 4.2h2.8" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/>
  </svg>
);

export const EjectIcon = (props: IconProps) => (
  <svg viewBox="0 0 26 29" aria-hidden focusable="false" {...props}>
    <path fill="currentColor" d="M13 0 26 18H0z"/> <rect fill="currentColor" x="0" y="23" width="26" height="6"/>
  </svg>
);

export const ExplorerIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <rect x="2.4" y="2.2" width="11.2" height="8.2" rx="1" fill="none" stroke="currentColor" strokeWidth="1.4"/> <path d="M0.4 11.7h15.2l-1.3 2.4H1.7z" fill="currentColor"/>
  </svg>
);

export const FilterIcon = (props: IconProps) => (
  <svg viewBox="0 0 11 11" aria-hidden focusable="false" {...props}>
    <rect x="0.5" y="0" width="2" height="11" fill="currentColor"/><rect x="4.5" y="0" width="6" height="11" fill="currentColor"/>
  </svg>
);

export const FolderIcon = (props: IconProps) => (
  <svg viewBox="0 0 14 12" aria-hidden focusable="false" {...props}>
    <path d="M0 2h5l1.5 1.5H14V11H0z" fill="currentColor"/>
  </svg>
);

export const GearIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <g fill="currentColor"> <rect x="6.9" y="0.6" width="2.2" height="3.2" transform="rotate(0 8 8)"/> <rect x="6.9" y="0.6" width="2.2" height="3.2" transform="rotate(45 8 8)"/> <rect x="6.9" y="0.6" width="2.2" height="3.2" transform="rotate(90 8 8)"/> <rect x="6.9" y="0.6" width="2.2" height="3.2" transform="rotate(135 8 8)"/> <rect x="6.9" y="0.6" width="2.2" height="3.2" transform="rotate(180 8 8)"/> <rect x="6.9" y="0.6" width="2.2" height="3.2" transform="rotate(225 8 8)"/> <rect x="6.9" y="0.6" width="2.2" height="3.2" transform="rotate(270 8 8)"/> <rect x="6.9" y="0.6" width="2.2" height="3.2" transform="rotate(315 8 8)"/> <path fillRule="evenodd" d="M8 1.7A6.3 6.3 0 1 0 8 14.3 6.3 6.3 0 0 0 8 1.7zm0 2.7a3.6 3.6 0 1 1 0 7.2 3.6 3.6 0 0 1 0-7.2z"/> </g>
  </svg>
);

export const HeadphonesIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <path d="M2.4 10.4V8.4a5.6 5.6 0 0 1 11.2 0v2.0" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/> <rect x="1.3" y="9.7" width="2.9" height="4.4" rx="1.35" fill="currentColor"/> <rect x="11.8" y="9.7" width="2.9" height="4.4" rx="1.35" fill="currentColor"/>
  </svg>
);

export const HistoryIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <circle cx="8" cy="8" r="5.6" fill="none" stroke="currentColor" strokeWidth="1.4"/> <path d="M8 4.6V8l2.6 1.6" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
);

export const InfoIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <circle cx="8" cy="8" r="6.4" fill="currentColor"/> <rect x="7.1" y="6.6" width="1.8" height="5.0" rx="0.6" fill="#000"/> <circle cx="8" cy="4.6" r="1.05" fill="#000"/>
  </svg>
);

export const LayoutBrowserIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <rect x="1.5" y="3.4" width="13" height="9.2" fill="none" stroke="currentColor" strokeWidth="1.4"/><path d="M1.5 6.6h13" stroke="currentColor" strokeWidth="1.4"/>
  </svg>
);

export const LayoutDualIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <rect x="1.5" y="5.4" width="8.4" height="7.2" fill="none" stroke="currentColor" strokeWidth="1.4"/><rect x="6.1" y="3.4" width="8.4" height="7.2" fill="none" stroke="currentColor" strokeWidth="1.4"/>
  </svg>
);

export const LayoutOneIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <rect x="1.5" y="4" width="13" height="8" fill="none" stroke="currentColor" strokeWidth="1.4"/><rect x="3.8" y="6.4" width="3.2" height="3.2" fill="currentColor"/>
  </svg>
);

export const LayoutSimpleIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <rect x="1.5" y="5.6" width="13" height="4.8" fill="none" stroke="currentColor" strokeWidth="1.4"/>
  </svg>
);

export const LayoutTwoIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <rect x="1.5" y="3" width="13" height="4.4" fill="none" stroke="currentColor" strokeWidth="1.4"/><rect x="1.5" y="8.6" width="13" height="4.4" fill="none" stroke="currentColor" strokeWidth="1.4"/>
  </svg>
);

export const LinkOnIcon = (props: IconProps) => (
  <svg viewBox="0 0 28 28" aria-hidden focusable="false" {...props}>
    <circle cx="6.5" cy="21.5" r="3.4" fill="currentColor"/> <path fill="none" stroke="currentColor" strokeWidth="4.2" strokeLinecap="butt" d="M6.5 11.5a10 10 0 0 1 10 10"/> <path fill="none" stroke="currentColor" strokeWidth="4.2" strokeLinecap="butt" d="M6.5 3.5a18 18 0 0 1 18 18"/>
  </svg>
);

export const LinkIcon = (props: IconProps) => (
  <svg viewBox="0 0 28 28" aria-hidden focusable="false" {...props}>
    <path fill="currentColor" d="M2 8.5h15V4.5l9 6-9 6v-4H2zM26 19.5H11v4l-9-6 9-6v4h15z"/>
  </svg>
);

export const ListIcon = (props: IconProps) => (
  <svg viewBox="0 0 14 12" aria-hidden focusable="false" {...props}>
    <rect x="1" y="1" width="12" height="10" fill="none" stroke="currentColor" strokeWidth="1.4"/> <path d="M1 4h12M1 7.5h12M4.5 4v7" stroke="currentColor" strokeWidth="1.4"/>
  </svg>
);

export const LockIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <path d="M5.1 7.4V5.4a2.9 2.9 0 0 1 5.8 0v2.0" fill="none" stroke="currentColor" strokeWidth="1.5"/> <rect x="3.2" y="7.2" width="9.6" height="7.0" rx="1.1" fill="currentColor"/>
  </svg>
);

export const LoopInIcon = (props: IconProps) => (
  <svg viewBox="0 0 15 6" aria-hidden focusable="false" {...props}>
    <path fill="currentColor" d="M0 3h3l3-3v3h9v3H0z"/>
  </svg>
);

export const LoopOutIcon = (props: IconProps) => (
  <svg viewBox="0 0 15 6" aria-hidden focusable="false" {...props}>
    <path fill="currentColor" d="M15 3h-3L9 0v3H0v3h15z"/>
  </svg>
);

export const MagnifierMinusIcon = (props: IconProps) => (
  <svg viewBox="0 0 14 14" aria-hidden focusable="false" {...props}>
    <circle cx="5.75" cy="5.75" r="4.75" fill="none" stroke="currentColor" strokeWidth="1.5"/> <path d="M9.4 9.4 13 13" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/> <path d="M3.4 5.75h4.7" fill="none" stroke="currentColor" strokeWidth="1.3"/>
  </svg>
);

export const MagnifierPlusIcon = (props: IconProps) => (
  <svg viewBox="0 0 14 14" aria-hidden focusable="false" {...props}>
    <circle cx="5.75" cy="5.75" r="4.75" fill="none" stroke="currentColor" strokeWidth="1.5"/> <path d="M9.4 9.4 13 13" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"/> <path d="M5.75 3.4v4.7M3.4 5.75h4.7" fill="none" stroke="currentColor" strokeWidth="1.3"/>
  </svg>
);

export const MetronomeIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <rect x="2.6" y="8.4" width="2.4" height="5.4" fill="currentColor"/> <rect x="6.8" y="4.6" width="2.4" height="9.2" fill="currentColor"/> <rect x="11.0" y="6.8" width="2.4" height="7.0" fill="currentColor"/>
  </svg>
);

export const NoteIcon = (props: IconProps) => (
  <svg viewBox="0 0 14 12" aria-hidden focusable="false" {...props}>
    <path d="M9 0v8.2a2.3 2.3 0 1 1-1.4-2.1V2.2L4 3.2v6.2a2.3 2.3 0 1 1-1.4-2.1V1.6z" fill="currentColor"/>
  </svg>
);

export const PrefAboutIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <path fill="currentColor" fillRule="evenodd" d="M8 .5a7.5 7.5 0 1 1 0 15 7.5 7.5 0 0 1 0-15zm0 1.6a5.9 5.9 0 1 0 0 11.8A5.9 5.9 0 0 0 8 2.1zM8 6.6c.5 0 .9.4.9.9v4a.9.9 0 0 1-1.8 0v-4c0-.5.4-.9.9-.9zm0-2.8a1.1 1.1 0 1 1 0 2.2 1.1 1.1 0 0 1 0-2.2z"/>
  </svg>
);

export const PrefAdvancedIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 12" aria-hidden focusable="false" {...props}>
    <g fill="currentColor"> <rect x="0" y="0.5" width="16" height="1.6"/> <rect x="0" y="5.2" width="16" height="1.6"/> <rect x="0" y="9.9" width="16" height="1.6"/> </g>
  </svg>
);

export const PrefAnalysisIcon = (props: IconProps) => (
  <svg viewBox="0 0 18 14" aria-hidden focusable="false" {...props}>
    <g fill="currentColor"> <rect x="0" y="5" width="1.6" height="4"/> <rect x="2.8" y="3" width="1.6" height="8"/> <rect x="5.6" y="4" width="1.6" height="6"/> <rect x="8.2" y="0" width="1.6" height="14"/> <rect x="10.8" y="4" width="1.6" height="6"/> <rect x="13.6" y="3" width="1.6" height="8"/> <rect x="16.4" y="5" width="1.6" height="4"/> </g>
  </svg>
);

export const PrefAudioIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <path d="M1 5.5h3.4L9 2v12L4.4 10.5H1z" fill="currentColor"/> <rect x="11" y="5.5" width="2.6" height="5" fill="currentColor"/>
  </svg>
);

export const PrefDjSystemIcon = (props: IconProps) => (
  <svg viewBox="0 0 18 14" aria-hidden focusable="false" {...props}>
    <rect x="0.7" y="0.7" width="16.6" height="12.6" rx="1" fill="none" stroke="currentColor" strokeWidth="1.4"/> <circle cx="5.5" cy="7" r="2.8" fill="none" stroke="currentColor" strokeWidth="1.3"/> <circle cx="5.5" cy="7" r="0.9" fill="currentColor"/> <g fill="currentColor"> <rect x="10.5" y="3.5" width="4.5" height="1.3"/> <rect x="10.5" y="6.3" width="4.5" height="1.3"/> <rect x="10.5" y="9.1" width="4.5" height="1.3"/> </g>
  </svg>
);

export const PrefKeyboardIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <path fill="currentColor" fillRule="evenodd" d="M2 0.5h12A1.5 1.5 0 0 1 15.5 2v12a1.5 1.5 0 0 1-1.5 1.5H2A1.5 1.5 0 0 1 .5 14V2A1.5 1.5 0 0 1 2 .5zM7 3.5 3.6 12.8h1.9l.8-2.4h3.4l.8 2.4h1.9L9 3.5zm1 2.4L6.8 8.9h2.4z"/>
  </svg>
);

export const PrefViewIcon = (props: IconProps) => (
  <svg viewBox="0 0 18 13" aria-hidden focusable="false" {...props}>
    <path d="M9 1C5.2 1 2.2 3.6 1 6.5 2.2 9.4 5.2 12 9 12s6.8-2.6 8-5.5C15.8 3.6 12.8 1 9 1z" fill="none" stroke="currentColor" strokeWidth="1.4"/> <circle cx="9" cy="6.5" r="2.6" fill="currentColor"/>
  </svg>
);

export const RecordIcon = (props: IconProps) => (
  <svg viewBox="0 0 100 100" aria-hidden focusable="false" {...props}>
    <path fill="currentColor" fillRule="evenodd" d="M50 7a43 43 0 1 0 0 86 43 43 0 0 0 0-86zm0 31a12 12 0 1 0 0 24 12 12 0 0 0 0-24z"/>
  </svg>
);

export const ReloadIcon = (props: IconProps) => (
  <svg viewBox="0 0 12 15" aria-hidden focusable="false" {...props}>
    <path d="M9.6 4.2A4.6 4.6 0 0 0 2 5.6" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/> <path d="M2.4 9.8A4.6 4.6 0 0 0 10 8.4" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/> <path d="M8.2 1.2 10.2 4.4 6.6 4.6z" fill="currentColor"/> <path d="M3.8 13.8 1.8 10.6 5.4 10.4z" fill="currentColor"/>
  </svg>
);

export const SortDownIcon = (props: IconProps) => (
  <svg viewBox="0 0 12 12" aria-hidden focusable="false" {...props}>
    <path d="M6 0.6v9.9M2.2 6.7 6 10.5l3.8-3.8" fill="none" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
);

export const SortUpIcon = (props: IconProps) => (
  <svg viewBox="0 0 12 12" aria-hidden focusable="false" {...props}>
    <path d="M6 11.4V1.5M2.2 5.3 6 1.5l3.8 3.8" fill="none" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
);

export const SpinnerIcon = (props: IconProps) => (
  <svg viewBox="0 0 10 16" aria-hidden focusable="false" {...props}>
    <path d="m1.5 5.5 3.5-3.5 3.5 3.5M1.5 10.5 5 14l3.5-3.5" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
);

export const SubBrowseIcon = (props: IconProps) => (
  <svg viewBox="0 0 18 18" aria-hidden focusable="false" {...props}>
    <rect x="3" y="4" width="6" height="10" fill="currentColor"/> <rect x="3.5" y="4.5" width="11" height="9" fill="none" stroke="currentColor" strokeWidth="1"/>
  </svg>
);

export const TickIcon = (props: IconProps) => (
  <svg viewBox="0 0 12 8" aria-hidden focusable="false" {...props}>
    <path d="M1 4.1L4.1 7 11 1" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
);

export const TwistyIcon = (props: IconProps) => (
  <svg viewBox="0 0 8 8" aria-hidden focusable="false" {...props}>
    <path d="m2.6 1.4 3 2.6-3 2.6" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
);
