/**
 * Interface icons. GENERATED by `pnpm icons` from `design/icons/ui/*.svg` —
 * edit the SVGs, not this file.
 *
 * Every icon paints in `currentColor`, so colour comes from the CSS token on
 * whatever contains it rather than from the icon.
 */
import type { SVGProps } from "react";

type IconProps = SVGProps<SVGSVGElement>;

export const FolderIcon = (props: IconProps) => (
  <svg viewBox="0 0 14 12" aria-hidden focusable="false" {...props}>
    <path d="M0 2h5l1.5 1.5H14V11H0z" fill="currentColor"/>
  </svg>
);

export const GearIcon = (props: IconProps) => (
  <svg viewBox="0 0 16 16" aria-hidden focusable="false" {...props}>
    <circle cx="8" cy="8" r="2.6" fill="none" stroke="currentColor" strokeWidth="1.4"/> <g stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"> <path d="M8 1.2v2.0M8 12.8v2.0M1.2 8h2.0M12.8 8h2.0"/> <path d="M3.2 3.2l1.4 1.4M11.4 11.4l1.4 1.4M12.8 3.2l-1.4 1.4M4.6 11.4l-1.4 1.4"/> </g>
  </svg>
);

export const ListIcon = (props: IconProps) => (
  <svg viewBox="0 0 14 12" aria-hidden focusable="false" {...props}>
    <rect x="1" y="1" width="12" height="10" fill="none" stroke="currentColor" strokeWidth="1.4"/> <path d="M1 4h12M1 7.5h12M4.5 4v7" stroke="currentColor" strokeWidth="1.4"/>
  </svg>
);

export const NoteIcon = (props: IconProps) => (
  <svg viewBox="0 0 14 12" aria-hidden focusable="false" {...props}>
    <path d="M9 0v8.2a2.3 2.3 0 1 1-1.4-2.1V2.2L4 3.2v6.2a2.3 2.3 0 1 1-1.4-2.1V1.6z" fill="currentColor"/>
  </svg>
);

export const SortDownIcon = (props: IconProps) => (
  <svg viewBox="0 0 12 12" aria-hidden focusable="false" {...props}>
    <path d="M6 0.6v9.9M2.2 6.7 6 10.5l3.8-3.8" fill="none" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
);

export const SortUpIcon = (props: IconProps) => (
  <svg viewBox="0 0 12 12" aria-hidden focusable="false" {...props}>
    <path d="M6 11.4V1.5M2.2 5.3 6 1.5l3.8 3.8" fill="none" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
);

export const TwistyIcon = (props: IconProps) => (
  <svg viewBox="0 0 8 8" aria-hidden focusable="false" {...props}>
    <path d="m2.6 1.4 3 2.6-3 2.6" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
);
