/**
 * Generates src/styles/tokens.css from design/tokens/tokens.json.
 * Committed output; CI re-runs this and fails on drift.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, URL } from "node:url";

type Token = { value: string; source?: string; $comment?: string };
type Group = Record<string, Token>;
type Tokens = { color: Group; size: Group; font: Group; $comment?: string };

const root = (p: string) => fileURLToPath(new URL(`../${p}`, import.meta.url));
const tokens = JSON.parse(readFileSync(root("design/tokens/tokens.json"), "utf8")) as Tokens;

const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
const emit = (prefix: string, group: Group) =>
  Object.entries(group)
    .filter(([k]) => !k.startsWith("$"))
    .map(([k, t]) => `  --${prefix}-${kebab(k)}: ${t.value};${t.source ? ` /* ${t.source} */` : ""}`)
    .join("\n");

const css = `/* GENERATED by scripts/build-tokens.ts from design/tokens/tokens.json — do not edit by hand. */
:root {
${emit("c", tokens.color)}

${emit("s", tokens.size)}

${emit("f", tokens.font)}
}

/* rekordbox export mode is a single dark design; we commit to it rather than
   deriving a light theme, but every color is set explicitly so the page never
   borrows the host's ground. */
:root[data-os="windows"] {
  --f-ui: "Segoe UI", system-ui, sans-serif;
}
:root[data-os="macos"] {
  --f-ui: "Lucida Grande", "Helvetica Neue", Helvetica, system-ui, sans-serif;
}
`;

writeFileSync(root("src/styles/tokens.css"), css);
console.log(`wrote src/styles/tokens.css (${Object.keys(tokens.color).length} colors, ${Object.keys(tokens.size).length} sizes)`);
