/**
 * Generates src/styles/tokens.css from design/tokens/theme.json.
 * Run: pnpm tokens. Rewrites the committed CSS; release CI regenerates it to
 * check for drift. The configured design input must exist in this checkout.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, URL } from "node:url";

type Token = { value: string; source?: string; $comment?: string };
type Group = Record<string, Token>;
type Tokens = { color: Group; size: Group; font: Group; $comment?: string };

const root = (p: string) => fileURLToPath(new URL(`../${p}`, import.meta.url));
const tokens = JSON.parse(readFileSync(root("design/tokens/theme.json"), "utf8")) as Tokens;

const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
const emit = (prefix: string, group: Group) =>
  Object.entries(group)
    .filter(([k]) => !k.startsWith("$"))
    .map(([k, t]) => `  --${prefix}-${kebab(k)}: ${t.value};${t.source ? ` /* ${t.source} */` : ""}`)
    .join("\n");

const css = `/* GENERATED by scripts/build-tokens.ts from design/tokens/theme.json — do not edit by hand. */
:root {
${emit("c", tokens.color)}

${emit("s", tokens.size)}

${emit("f", tokens.font)}
}

/* rekordbox export mode is a single dark design; we commit to it rather than
   deriving a light theme, but every color is set explicitly so the page never
   borrows the host's ground.

   No per-OS font override: the face was measured as Arial (see
   design/measure/font-report.json) and Arial ships on both macOS and Windows,
   so the same stack reproduces the app on both targets. */
`;

writeFileSync(root("src/styles/tokens.css"), css);
console.log(`wrote src/styles/tokens.css (${Object.keys(tokens.color).length} colors, ${Object.keys(tokens.size).length} sizes)`);
