/**
 * Generates `src/components/icons.tsx` from `design/icons/ui/*.svg`.
 *
 * The SVGs are the source. Inlining them into a module rather than importing
 * them as files keeps the icons out of the network path entirely — they are a
 * few hundred bytes each, and a request per icon is a request too many for
 * something that must paint in the first frame.
 *
 * `pnpm icons`
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const SOURCE = join(import.meta.dirname, "../design/icons/ui");
const TARGET = join(import.meta.dirname, "../src/components/icons.tsx");

/** `sort-up` → `SortUpIcon`. */
function componentName(file: string): string {
  const stem = file.replace(/\.svg$/, "");
  const camel = stem.replace(/(^|-)(.)/g, (_, __, c: string) => c.toUpperCase());
  return `${camel}Icon`;
}

/** Rewrites SVG attributes into the JSX spellings React expects. */
function toJsx(svg: string): string {
  return svg
    .replace(/<\?xml[^>]*\?>\s*/g, "")
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/\sxmlns="[^"]*"/g, "")
    .replace(/-([a-z])/g, (match, letter: string, offset: number, whole: string) => {
      // Only inside attribute names: a hyphen in path data must survive.
      const before = whole.slice(0, offset);
      const lastQuote = Math.max(before.lastIndexOf('"'), before.lastIndexOf("'"));
      const lastSpace = before.lastIndexOf(" ");
      return lastSpace > lastQuote ? letter.toUpperCase() : match;
    })
    .replace(/\s+/g, " ")
    .trim();
}

const files = readdirSync(SOURCE).filter((f) => f.endsWith(".svg")).sort();
const parts = files.map((file) => {
  const svg = toJsx(readFileSync(join(SOURCE, file), "utf8"));
  const inner = svg.replace(/^<svg([^>]*)>/, "").replace(/<\/svg>$/, "").trim();
  const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1] ?? "0 0 12 12";
  return `export const ${componentName(file)} = (props: IconProps) => (
  <svg viewBox="${viewBox}" aria-hidden focusable="false" {...props}>
    ${inner}
  </svg>
);`;
});

const output = `/**
 * Interface icons. GENERATED by \`pnpm icons\` from \`design/icons/ui/*.svg\` —
 * edit the SVGs, not this file.
 *
 * Every icon paints in \`currentColor\`, so colour comes from the CSS token on
 * whatever contains it rather than from the icon.
 */
import type { SVGProps } from "react";

type IconProps = SVGProps<SVGSVGElement>;

${parts.join("\n\n")}
`;

writeFileSync(TARGET, output);
console.warn(`icons: wrote ${files.length} components to ${TARGET}`);
